-- Alterações ItemFechamentoEstoque  
ALTER TABLE ItemFechamentoEstoque DROP COLUMN DT_FECHAMENTO;
ALTER TABLE ItemFechamentoEstoque DROP COLUMN ID_ESTOQUE;
ALTER TABLE ItemFechamentoEstoque DROP COLUMN pIN_ERRO;
ALTER TABLE ItemFechamentoEstoque ADD ID_PRODUTO INT NOT NULL;
ALTER TABLE ItemFechamentoEstoque ADD QN_FINAL  INT NOT NULL;
ALTER TABLE ItemFechamentoEstoque ADD QN_QUEBRAS  INT NOT NULL;
ALTER TABLE ItemFechamentoEstoque ADD QN_CORTESIAS  INT NOT NULL;
ALTER TABLE ItemFechamentoEstoque ADD IN_DIVERGENCIA  INT NOT NULL;
ALTER TABLE ItemFechamentoEstoque ADD QN_DIVERGENCIA  INT NOT NULL;