CREATE TABLE Cargo (
    ID_CARGO INT PRIMARY KEY,
    TX_NOME VARCHAR(255) NOT NULL
);

CREATE TABLE Empresa (
    ID_EMPRESA INT PRIMARY KEY,
    TX_RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    TX_CNPJ VARCHAR(18) NOT NULL,
    TX_TOKEN VARCHAR(255),
    IN_ATIVO BIT NOT NULL DEFAULT (0),
    TX_EMAIL VARCHAR(255) NOT NULL,
    DT_CRIACAO DATETIME NOT NULL
);

CREATE TABLE Funcionario (
    ID_FUNCIONARIO INT PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    ID_CARGO INT NOT NULL,
    TX_NOME VARCHAR(255) NOT NULL,
    TX_CPF VARCHAR(14) NOT NULL,
    TX_EMAIL VARCHAR(255),
    TX_TELEFONE VARCHAR(20),
    DT_ENTRADA DATE NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES Empresa(ID_EMPRESA),
    FOREIGN KEY (ID_CARGO) REFERENCES Cargo(ID_CARGO)
);

CREATE TABLE Fornecedor (
    ID_FORNECEDOR INT PRIMARY KEY,
    TX_NOME VARCHAR(255) NOT NULL
);

CREATE TABLE Marca (
    ID_MARCA INT PRIMARY KEY,
    TX_NOME VARCHAR(255) NOT NULL
);

CREATE TABLE Usuario (
    ID_USUARIO INT PRIMARY KEY,
    ID_FUNCIONARIO INT NOT NULL,
    TX_LOGIN VARCHAR(255) NOT NULL,
    TX_SENHA VARCHAR(255) NOT NULL,
    IN_ATIVO BIT NOT NULL DEFAULT (0),
    TX_EMAIL VARCHAR(255),
    DT_CRIACAO DATETIME NOT NULL,
    FOREIGN KEY (ID_FUNCIONARIO) REFERENCES Funcionario(ID_FUNCIONARIO)
);

CREATE TABLE Estoque (
    ID_ESTOQUE INT PRIMARY KEY,
    ID_EMPRESA INT NOT NULL,
    ID_RESPONSAVEL INT NOT NULL,
    TX_NOME VARCHAR(255) NOT NULL,
    IN_ATIVO BIT NOT NULL DEFAULT (0),
    FOREIGN KEY (ID_EMPRESA) REFERENCES Empresa(ID_EMPRESA),
    FOREIGN KEY (ID_RESPONSAVEL) REFERENCES Funcionario(ID_FUNCIONARIO)
);

CREATE TABLE Produto (
    ID_PRODUTO INT PRIMARY KEY,
    ID_MARCA INT NOT NULL,
    TX_NOME VARCHAR(255) NOT NULL,
    TX_DESCRICAO VARCHAR(255),
    VALOR FLOAT NOT NULL,
    FOREIGN KEY (ID_MARCA) REFERENCES Marca(ID_MARCA)
);

CREATE TABLE EstoqueProduto (
    ID_ESTOQUE INT,
    ID_PRODUTO INT,
    QN_ESTOQUE INT NOT NULL,
    PRIMARY KEY (ID_ESTOQUE, ID_PRODUTO),
    FOREIGN KEY (ID_ESTOQUE) REFERENCES Estoque(ID_ESTOQUE),
    FOREIGN KEY (ID_PRODUTO) REFERENCES Produto(ID_PRODUTO)
);

CREATE TABLE FechamentoEstoque (
    ID_FECHAMENTO INT PRIMARY KEY,
    ID_ESTOQUE INT NOT NULL,
    DT_FECHAMENTO DATETIME NOT NULL,
    IN_ERRO BIT NOT NULL DEFAULT (0),
    FOREIGN KEY (ID_ESTOQUE) REFERENCES Estoque(ID_ESTOQUE)
);

CREATE TABLE ItemFechamentoEstoque (
    ID_FECHAMENTO INT PRIMARY KEY,
    ID_ESTOQUE INT NOT NULL,
    DT_FECHAMENTO DATETIME NOT NULL,
    IN_ERRO BIT NOT NULL DEFAULT (0),
    FOREIGN KEY (ID_ESTOQUE) REFERENCES Estoque(ID_ESTOQUE)
);

CREATE TABLE MovimentacaoEstoque (
    ID_MOVIMENTACAO INT PRIMARY KEY,
    ID_ESTOQUE INT NOT NULL,
    ID_USUARIO INT NOT NULL,
    DT_MOVIMENTACAO DATETIME NOT NULL,
    IN_ENTRADA BIT NOT NULL DEFAULT (0),
    IN_PROCESSADO BIT NOT NULL DEFAULT (0),
    FOREIGN KEY (ID_ESTOQUE) REFERENCES Estoque(ID_ESTOQUE),
    FOREIGN KEY (ID_USUARIO) REFERENCES Usuario(ID_USUARIO)
);

CREATE TABLE ItemMovimentacaoEstoque (
    ID_ITEM_MOVIMENTACAO INT PRIMARY KEY,
    ID_MOVIMENTACAO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QN_MOVIMENTACAO INT NOT NULL,
    IN_PROCESSADO BIT NOT NULL DEFAULT (0),
    FOREIGN KEY (ID_MOVIMENTACAO) REFERENCES MovimentacaoEstoque(ID_MOVIMENTACAO),
    FOREIGN KEY (ID_PRODUTO) REFERENCES Produto(ID_PRODUTO)
);