-- Criar EstoqueUsuario
CREATE TABLE EstoqueUsuario (
	ID_ESTOQUE INT NOT NULL,
	ID_USUARIO INT NOT NULL,	
	IN_ATIVO BIT NOT NULL DEFAULT(0),
	FOREIGN KEY (ID_USUARIO) REFERENCES Usuario(ID_USUARIO),
	FOREIGN KEY (ID_ESTOQUE) REFERENCES Estoque(ID_ESTOQUE)
);